### ISSUE TITLE
How to unsubscribe?

### ISSUE THREAD

**Issue by jonnius** [S60W79/warnapp-deutschland#3]
First of all, thank you very much for this app!

I subscribed to `Postillion` for testing purpose before subscribing to my Landkreis. How can I unsubscribe from it again?

I tried by deleting all app data. This gets me rid of the Postillion posts in-app, but I still get its push notifications.

**Comment by S60W79** [comment]
Hi thanks for your feedback (:
Deleting the App Data won't unsuscribe you from the push notifications, because the server isn't told to not-send the notifications anymore then. The unsuscribing from push should happen when you delete the Postillion (or landkreis) (in the list of the kreises: swipe there and tip on the bin symbol).
The problem is, that if the server is down, this unregister signal isn't recived. I am currently working on popups, which are to signal the user that subscribing or unsuscribing failed. Currently the workaround is to enroll for the kreis again and then unsuscribe.
Best greetings

**Comment by jonnius** [comment]
Where do I find the list of kreises?

**Comment by S60W79** [comment]
It is in the settings, and then the list symbol (2nd from the right).
Maybe I should do some design changes sorry for that...

**Comment by jonnius** [comment]
Thanks that worked!

I am not an UX expert, but where it is currently located, I didn't find it. ;)
